### ISSUE TITLE
Doesn't work with the IRI version 1.4.1.7

### ISSUE THREAD

**Issue by DanielPollithy** [schierlm/private-iota-testnet#13]
I had to switch back to 1.4.1.6 in order to run the private node. 

It had the problem with the latestSubtangleMilestone: and the latestSolidSubtangleMilestone which were not referencing to the same.

BTW: great tutorial!

**Comment by schierlm** [comment]
Works fine for me with 1.4.2.1. Not sure whether the bug has been fixed meanwhile (probably [this one](https://github.com/iotaledger/iri/commit/2def8664760acc74ea0785a3b1c77b26e7416aa6)?).

If you are still having problems, feel free to reopen.
