### ISSUE TITLE
The CLI  App thinks that the tangle is out of sync.

### ISSUE THREAD

**Issue by NemesisFLX** [schierlm/private-iota-testnet#18]
Error: Request Error: This operations cannot be executed: The subtangle has not been updated yet.

This error will be produced after i type balance to show my balance or when i try to generate an address:

`iota (http://127.0.0.1:14700 434525/434525): address
One minute while we generate the address.
The address is DDHUOLNTGMXRRLQLNLQACPJITLHYVCVQIXNEDXYNSTPZULFJXFOAZEFFSBANNYFJH9JDHBIDQGUNLUCQXYIDOIG9SX
Now we will register that address into the iota tangle.  One moment.
Error: Request Error: This operations cannot be executed: The subtangle has not been updated yet.
`

I tried to get the node info and it shows only this:

`latestMilestone:                    999999999999999999999999999999999999999999999999999999999999999999999999999999999
latestMilestoneIndex:               434525
latestSolidSubtangleMilestone:      999999999999999999999999999999999999999999999999999999999999999999999999999999999
latestSolidSubtangleMilestoneIndex: 434525
`

**Comment by schierlm** [comment]
Did you run the coordinator?

If yes, make sure that your iri is the current stable version and not the dev branch which already includes some changes for the update next weekend (including a new Coordinator address for testnet).

**Comment by schierlm** [comment]
When iri is run with --testnet, it should not verify signatures, so the only way for the transaction to not be accepted as a milestone would be that it is using the wrong coordinator address.

What confuses me is the number of tips you are having. Most clients will refuse to create transactions if there is no milestone, and the coordinator only creates 2 transactions. So where are the 7 tips from?

Perhaps you should delete your testnetDB and start over?

**Comment by NemesisFLX** [comment]
I did delete the db and recompiled everything, but it still doesent work. IRI registers the two transactions from the coo,
`04/28 19:47:13.431 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 2
`
after i ran the coo once, but the cli app shows still the same milestone.

P.S: The many tips came from running the periodic coo that you had as an option.

**Comment by schierlm** [comment]
Ok. But still I have no clue what you did differently than the others (I get positive feedback from somebody new every other day).

I would
- check again the version of iri you were using; `git rev-parse HEAD` in case you cloned it from git (should be fee959ccbce5da0289cb54451994a0482c52305c)
- check the local differences you made to iri `git diff` (you can attach the diff so that I can have a look, if you prefer)
- clean and recompile iri just to make sure
- verify that you started iri with the parameters in my README
- check that you did not modify the Coordinator from my repo (`git diff`)
- clean and recompile the Coordinator
- try again

**Comment by music** [comment]
I was running into the same exact problem. It turns out on the git page for iri, the default branch is dev; I'm assuming you're running on that branch which is why you're running into problems. Switch to master and everything will work smoothly! @NemesisFLX

**Comment by NemesisFLX** [comment]
I had everything right as you described it, but it didn't work so out of despair i deleted all folders to iota-tools and iri and cloned it from scratch and now it works! I dont know what changed. Propably some leftovers from the dev branch compile. ¯\_(ツ)_/¯

Thanks for your help!
