### ISSUE TITLE
All transaction pending,how to tangle in the private testnet??

### ISSUE THREAD

**Issue by lhfly5201314** [schierlm/private-iota-testnet#21]
Hi,friend!Thanks so much for your wonderful tutorial.It really inspires me!
But now I got some issues.When I finished the address attached and transfering fund 
to another address,all the trasfers are pending...
How to implement the real tangle on my machine???
Thanks again!

**Comment by schierlm** [comment]
You will have to re-run the coordinator so that it can confirm some of
your transaction.

**Comment by lhfly5201314** [comment]
Got it,thanks,friend!

**Comment by lhfly5201314** [comment]
You really did a great work about this repo!
