### ISSUE TITLE
connect the private iota with the wallet's source code

### ISSUE THREAD

**Issue by MAYS-200753008** [schierlm/private-iota-testnet#22]
Dear team,
How can we connect the private iota testnet with the source code of the wallet?

**Comment by schierlm** [comment]
So you want to know how you can access the testnet in the official GUI wallet? Choose "Custom" in the node configuration and enter http://localhost:14700/ as the node.

**Comment by MAYS-200753008** [comment]
I did that, and it works fine with me. But I want to connect the JS lib with the private testnet iota.

**Comment by schierlm** [comment]
That's not different.

```
var iota = new IOTA({
    'provider': 'http://localhost:14700'
});
```
