### ISSUE TITLE
Full node installation 

### ISSUE THREAD

**Issue by MAYS-200753008** [schierlm/private-iota-testnet#23]
Dear team,
How can I add neighbors to my wallet, what ip I will provide in neighbors box?

**Comment by schierlm** [comment]
Hello MAYS-200753008,

I am not sure what you want to achieve.

If you want to run multiple testnet nodes, you can add them to each other as neighbors. Just run them on different IP addresses, and make sure all of them use the same `Snapshot.txt`.

Running more than one node on the same IP might also work, but you have to configure all ports (not only the API port) and make sure they are all distinct.

If you want to use your testnet in the wallet, choose "Custom Node" and enter one of your node's IP addresses.

In case you are running only one node on the same machine as the wallet, use localhost or 127.0.0.1.

**Comment by MAYS-200753008** [comment]
Hello schierlm,
Thanks for the helpful answers.

Yes, I want to run multiple testnet nodes on different devices and I want to add them as neighbors, I'm doing what you said by copying the same snapshot file for both of them. But also I'm getting errors that failed to connect to that IP address. Any further information you can provide me?

**Comment by schierlm** [comment]
The API port is different from the port that is used to communicate between nodes. f you try to add neighbor's API port, it will fail. Also make sure that there is no firewall rule that prevents communication.

Other than that, I cannot really help you without knowing your setup (config files, ip addresses, ports) better.

**Comment by MAYS-200753008** [comment]
Dear Schierlm,

I'm still getting issues with connecting the two testnet wallets on different PCs with different IPs. Could you please inform me what should be place in the following fields of node configuration.
Node port:
UDP Receiver port:
TCP Receiver port:

Also for the neighboring nodes:
udp://ip_of_second_pc:server_port_of_second_pc 
"Is the above format correct !!"

I tried to setup the ports, but I'm getting an error message " The server port in use, please close the services that uses this port". 
I putting the server port same as the port that i'm using here: java -jar iri-1.4.2.4.jar --testnet --testnet-no-coo-validation --snapshot=Snapshot.txt -p 14700 => if I changed the port It will not synced

Note: the light node version working without any issue, the problem that I'm facing is in full node configuration.

Thanks in advance for the help.

**Comment by schierlm** [comment]
So you are trying to use the full node included in the official GUI wallet? Sorry, no idea, i never used that (as the general consensus seems to be to not use that but use standalone iri instead).
