### ISSUE TITLE
Issue about running multiple nodes in IOTA private testnet.

### ISSUE THREAD

**Issue by nengliangZ** [schierlm/private-iota-testnet#26]
Thanks for the code, I can run the first node with snapshot file and use the coordinator to create a milestone perfectly. 
But when I want to run the second node in my private machine, it always returns with errors:

<img width="1656" alt="screen shot 2018-08-17 at 11 36 10 am" src="https://user-images.githubusercontent.com/26139511/44243450-7de3eb00-a212-11e8-8086-bff5bbba7f6a.png">

I do change the second port to a new port that is different from the first node. And I don't run the node in a docker container, just run the .jar file directly.

I'm using MacOS High Sierra 10.13.4.

I doubt that maybe I need to run each node in a docker container? 

The final goal for me is to run a private network with a few full nodes that connect to each other, but there is little tutorial or resource about how to do this. So if anyone happens to have similar experiences, please offer me some advice! Thank you!

Any suggestions about this question would be very helpful! Thanks in advance!

**Comment by schierlm** [comment]
IRI uses more than just the API port. There is also a TCP neighbor port (`-t` switch), an UDP neighbor port (`-u` switch) and a ZMQ receiver port (`--zmq-port` switch). Each of them have to be unique for each node.

When pairing the nodes, use the TCP or UDP neighbor ports, not the API ports.

**Comment by nengliangZ** [comment]
@schierlm Thank you so much for the instruction, now I can successfully run two full nodes and they are neighbors. I think they can synchronize with each other since the following phenomenon: 

I use the light wallet of IOTA, and:
1. connect the wallet to node1, log in with seed1 (which generated in snapshot.log), and then make a transaction to an address that belongs to seed2 (which generated by a seed generator)
2. connect the wallet to node2, log in with any one of the two seeds, then this transaction will show at the wallet with a status of 'pending'.
3. the 'pending' status can change to 'confirmed' after I run the coordinator again.

My questions here are:

1. Is the above phenomenon shows that the two full nodes are successfully settled and be neighbors in this private network?

2. the two nodes paired with each other by adding the counterpart's TCP ports, but is it means that everytime a new node wants to add to this network, all the old nodes need to restart and change their config by adding the new node's TCP ports?

3. about the coordinator: in my private network, all the transactions can only be confirmed by running the coordinator? Is there any way to not include the coordinator and validate the transactions by the full nodes?

Many thanks in advance!

**Comment by schierlm** [comment]
1. yes.
2. You can add/remove nodes at runtime. There is also a GUI for that (Peer Manager). Also, you can run Nelson (when you want to be part of the mainnet) which will automatically pick random neighbors for you (from other nodes also running Nelson) and also add you to them.
3. Currently there is no way in IRI to use a different validation method than the coordinator. So no.
