### ISSUE TITLE
Run node in docker, how to config the snapshot and run coordinator?

### ISSUE THREAD

**Issue by nengliangZ** [schierlm/private-iota-testnet#27]
May I ask what if I want to run the IRI nodes in docker, how can I config the snapshot.txt and run coordinator to create milestone?

I can successfully run a node inside a docker on my local machine with the docker image pull from https://hub.docker.com/r/iotaledger/iri/ and change to the v1.4.2.4, which is compatible with your code.

My questions are:
1. when running iri in docker, we need to create a IRI ini file, but I don't know how to config snapshot.txt in this config file since it seems no specific variable to config snapshot.txt? And I don't know where to store this snapshot.txt as well.

2. coordinator doesn't work when I send the request to the node inside docker. The node can receive this request, but no milestone is created.
This is the result after I run the coordinator:
<img width="1339" alt="screen shot 2018-09-09 at 11 42 03 pm" src="https://user-images.githubusercontent.com/26139511/45265127-18d68a80-b48a-11e8-8b5c-565005230e77.png">

This is the result of the node's log:
<img width="1421" alt="screen shot 2018-09-09 at 11 41 44 pm" src="https://user-images.githubusercontent.com/26139511/45265131-1ffd9880-b48a-11e8-8d50-fd3fed91c848.png">

Any thought would be great! Thanks in advance!

**Comment by schierlm** [comment]
Are you sure you set the node to testnet, and disabled coo validation? Otherwise your node will not accept (unsigned) testnet milestones.

And I think the INI options are all there:

    DONT_VALIDATE_TESTNET_MILESTONE_SIG = true
    TESTNET = true
    SNAPSHOT_FILE = /path/to/your/snapshot.txt

About where to put the file, I cannot help you as I never used Docker. But probably there is some path where you can put it so that it gets copied into the container. Then just use an absolute path to it.

**Comment by nengliangZ** [comment]
@schierlm Thank you for your instruction, I should update my INI file in case anyone wants to do this by docker.
`
[IRI]
PORT = 14001
UDP_RECEIVER_PORT = 15001
TCP_RECEIVER_PORT = 16001
NEIGHBORS = udp://172.17.0.3:15002 ;this ip should be the ip of your docker container
TESTNET = TRUE
DONT_VALIDATE_TESTNET_MILESTONE_SIG = TRUE
SNAPSHOT_FILE = /iri/data/Snapshot.txt ; this should be the path which you mount the snapshot.txt into
IRI_OPTIONS = "--remote"
`

I run node by this command:
`docker run -d -p 14001:14001 -p 15001:15001/udp -v $(pwd)/config_1.ini:/iri/iota.ini --name iri1 -v $(pwd)/data:/iri/data iotaledger/iri:v1.4.2.4`

Question:
But this doesn't work for any the docker versions after v1.5.0 (includes 1.5.0) when I try to run docker container, I can't match the machine's ip to the docker's ip by 14001:14001. Anyone has idea?

**Comment by purplecity** [comment]
@nengliangZ 老哥 DONT_VALIDATE_TESTNET_MILESTONE_SIG这个字段是啥意思
