### ISSUE TITLE
Install private-iota-testnet

### ISSUE THREAD

**Issue by KevinKu** [schierlm/private-iota-testnet#4]
Hello~

"Get iota.lib.java and install it into your local Maven repository"

What mean is "install it into your local Maven repository"?

I clone "Private IOTA Testnet" and "iota.lib.java"

In "iota.lib.java" 's directory,I input "mvn install"
Then,in "Private IOTA Testnet" 's directory,I input "mvn package"

It has a error when project builds.
The error message is : 

[ERROR] Failed to execute goal on project iota-testnet-tools: Could not resolve dependencies for project org.iota:iota-testnet-tools:jar:0.1-SNAPSHOT: Could not find artifact org.iota:jota:jar:0.9.3-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

So , how to fix it?

Thanks your answer~

**Comment by schierlm** [comment]
iota lib and iri are changed too frequently at the moment. Either use an older version of iri and iota.lib.js, or try the fixes I pushed a few minutes ago to this repo.
