### ISSUE TITLE
Zero balance in IOTA lite wallet 2.5.5

### ISSUE THREAD

**Issue by Geo-Joy** [schierlm/private-iota-testnet#6]
iam running the private node on http://localhost:14700
I connected the wallet to this ip:port

But Iam not able to see my balance in the wallet when logged in with the seed from Snapshot.txt

Any suggestions????

**Comment by Geo-Joy** [comment]
Sorry I used the wrong seed to check the balance!

**Comment by schierlm** [comment]
For the record: The snapshot.txt does not contain any seeds, it only contains addresses (without checksum). You have to take the seed (which is in Snapshot.log) and not the address to log in.

**Comment by Geo-Joy** [comment]
@schierlm yes it's snapshot.log
