### ISSUE TITLE
IOTA Wallet is unable to login under test node

### ISSUE THREAD

**Issue by vikulin** [schierlm/private-iota-testnet#9]
IOTA Wallet is unable to login under test node:

![iota light wallet 2 5 6 - iri 1 4 1 2_109](https://user-images.githubusercontent.com/743622/34445457-6f93ab26-ecdc-11e7-8b7d-177efc344989.png)
![iota light wallet 2 5 6 - iri 1 4 1 2_110](https://user-images.githubusercontent.com/743622/34445459-71b21e1a-ecdc-11e7-8956-7e7147b4c67a.png)

Test test node log:
12/29 19:07:27.437 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 2
12/29 19:07:37.438 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 2
12/29 19:07:47.439 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 2
12/29 19:08:02.440 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 2
12/29 19:08:17.441 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 2
12/29 19:08:32.441 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 2
12/29 19:08:42.442 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 2
12/29 19:08:52.443 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 2
12/29 19:09:07.444 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 2

**Comment by vikulin** [comment]
[Snapshot.txt](https://github.com/schierlm/private-iota-testnet/files/1593781/Snapshot.txt)

[Snapshot.sig.txt](https://github.com/schierlm/private-iota-testnet/files/1593782/Snapshot.sig.txt)

**Comment by vikulin** [comment]
Seed: YMVEOJFFALQKWDEMIHBG9F9GGJJLMMNDDGARW9YQZSSBSBCSBGQPCOKUYPAYCZHUGETUQUQPUUKKMGRLE

**Comment by vikulin** [comment]
private static String SNAPSHOT_PUBKEY = "IMDNEANVVWZIVWPUHWLHTOIDQODFSFGOAMWDJBIMRBTZDACBFKHSPGYBKNOGXJMXDFWLBNTJNXE9IDGKD";

**Comment by schierlm** [comment]
Perhaps you should do things you understand, or at least [be able to read instructions](https://github.com/schierlm/private-iota-testnet/blame/master/README.md#L41) :-(

When you open another bug report like this, I'll block your access to create new issues.

**Comment by vikulin** [comment]
Yes, I'm able and I read. I did run Coordinator as follow:

~ java -jar iota-testnet-tools-0.1-SNAPSHOT-jar-with-dependencies.jar Coordinator localhost 14265
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
New milestone created.

 Otherwise totalTransactions could be 0 instead of 2. You should be just more attentive.

**Comment by vikulin** [comment]
Pls reopen the issue.

**Comment by schierlm** [comment]
If you would hav ran the coordinator correctly, the latest milestone hash would be the milestone you just created and not 999...9. Probably you changed the coordinator address (either in the coordinator or in your iri), or probably you enabled milestone signature verification but ran the "not signing" coordinator?

**Comment by vikulin** [comment]
Yes, I used to run Coordinator but I can't run Signed one:

java -jar iota-testnet-tools-0.1-SNAPSHOT-jar-with-dependencies.jar iotatools.SignedCoordinator localhost 14265
Do you want Coordinator or SnapshotBuilder?

**Comment by vikulin** [comment]
root@gem-01:~# java -cp iota-testnet-tools-0.1-SNAPSHOT-jar-with-dependencies.jar iotatools.SignedCoordinator localhost 14265
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Coordinator address: RYFWNCDZRFDOHQSRUGJITNVAYBUPQAEZFKDYSVALVSWXMHSB9PCMOI9IRASPHJN9WZSOMWKTSOISMBJEN
Milestone index: 243001
Public subkey: KGDFIIMHB9WXFRMSAPVWSXBGKALKGKPGFLRQHQCVNJMHKNXESQCLBDSZGGDAGFUOVMTEQWMAUBIWPSVPF
Signed trunk transaction: NFMYIWYURHLRU9JEBBIRPALWPAOEJGLYFBGATHBYWNOVPLSSLDBXUDKWZDP9XFULJUCIYPGXBTEAC9999
jota.error.ArgumentException: [{"error":"Invalid trytes input","duration":11}]
	at jota.IotaAPICore.wrapCheckedException(IotaAPICore.java:71)
	at jota.IotaAPICore.storeTransactions(IotaAPICore.java:410)
	at iotatools.SignedCoordinator.newMilestone(SignedCoordinator.java:127)
	at iotatools.SignedCoordinator.main(SignedCoordinator.java:41)
Exception in thread "main" java.lang.IllegalAccessError: 500 {"exception":"Invalid transaction hash","duration":17}
	at jota.IotaAPICore.wrapCheckedException(IotaAPICore.java:79)
	at jota.IotaAPICore.broadcastTransactions(IotaAPICore.java:400)
	at iotatools.SignedCoordinator.newMilestone(SignedCoordinator.java:128)
	at iotatools.SignedCoordinator.main(SignedCoordinator.java:41)
root@gem-01:~#

**Comment by schierlm** [comment]
You had the same question about the unsigned coordinator and opened issue #8 for that. What MWM are you using? If more than 13, you have to patch the signed coordinator too.

**Comment by vikulin** [comment]
I corrected SignedCoordinator and it worked. Thanks.

2017-12-30 0:11 GMT+02:00 Michael Schierl <notifications@github.com>:

**Comment by vikulin** [comment]
My second node does not sync. Both of them discovered each other
12/31 09:37:41.185 [pool-5-thread-1] INFO
c.i.i.n.r.ReplicatorSinkProcessor - Opening sink 141.105.132.110
12/31 09:37:41.186 [pool-5-thread-1] INFO
c.i.i.n.r.ReplicatorSinkProcessor - Connecting sink 141.105.132.110
12/31 09:37:41.310 [pool-5-thread-1] INFO
c.i.i.n.r.ReplicatorSinkProcessor - ----- NETWORK INFO ----- Sink
141.105.132.110 is connected

Second node log keeps 0 transactions in log:
12/31 12:27:38.977 [pool-2-thread-2] INFO  com.iota.iri.network.Node -
toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 /
totalTransactions = 0

SeignedCoordinator was successfully ran on first node.

2017-12-31 11:52 GMT+02:00 Vadym Vikulin <vadym.vikulin@gmail.com>:

**Comment by schierlm** [comment]
I assume you already checked that both know each other via the same transport (i. e. both have TCP or both have UDP)? A node will silently drop packets from nodes they don't "know", and TCP vs. UDP is a common cause for that.

You also created some transactions on the "synched" side (regardless whether milestones, value transactions or just spam?) **after** adding the neighbors? As a node will not ask his neighbor for any missing transactions as long as he has received nothing from him, a network without any transactions will not make any efforts to get "new" nodes in sync, as the synced node will never ask the unsynced one and vice versa. Not a problem on the real network though as there are new transations at least every minute :)

If both are untrue, I'd suggest to install iota peer manager on both nodes and have a look at the transaction statistics (the live node should have sent all new transactions to the new node, and the new node should have received the same amount and not dropped any, and the new node should have made a few requests (for missing transactions) to the synced node, and the synced node should have found and sent all those transactions, too).

**Comment by vikulin** [comment]
3 ports are opened for both nodes. 14625 (TCP), 15600 (TCP), 14600 (UDP). Also I did transaction **after** adding the neighbor. My screenshot of the peer manager:
First node:
![selection_111](https://user-images.githubusercontent.com/743622/34909772-1b75ba7c-f8b0-11e7-8beb-70660b61e096.png)
First node after a milestone run:
![selection_112](https://user-images.githubusercontent.com/743622/34909774-20d93156-f8b0-11e7-9173-a029ed47b1e0.png)
Second node remains unsynced:
![selection_113](https://user-images.githubusercontent.com/743622/34909775-231ff314-f8b0-11e7-9fe1-8084dfdcde9d.png)

**Comment by vikulin** [comment]
You also can connect to them. Hosts are public.

**Comment by schierlm** [comment]
14265 is API port (verified it by connecting and querying neigbors) and 15600 is peer port (verified it by connecting and not getting any response as I am not your neighbor). 14625 is neither port (is closed).

Use the peer port for your neighbors (i. e. 15600) and try again :)
